import { Teacher } from "@/types/teacher";
export const data: Teacher[] = [
  {
    info: "Анкиенко Ирина Николаевна",
    subject: "Английский язык",
    exam: "ЕГЭ",
    years: "10 лет",
    balls: "98",
    img: "teacher.png",
    description: "Кислород водород и тд",
  },
  {
    info: "Анкиенко Ирина Николаевна",
    subject: "Русский язык",
    exam: "ЕГЭ",
    years: "10 лет",
    balls: "98",
    img: "",
    description: "Кислород водород и тд",
  },
  {
    info: "Макаричев Семён Вячеславович",
    subject: "Немецкий язык",
    exam: "ЕГЭ",
    years: "10 лет",
    balls: "98",
    img: "",
    description: "Кислород водород и тд",
  },
  {
    info: "Макаричев Семён Вячеславович",
    subject: "Немецкий язык",
    exam: "ЕГЭ",
    years: "10 лет",
    balls: "98",
    img: "",
    description: "Кислород водород и тд",
  },
  {
    info: "Макаричев Семён Вячеславович",
    subject: "Немецкий язык",
    exam: "ЕГЭ",
    years: "10 лет",
    balls: "98",
    img: "",
    description: "Кислород водород и тд",
  },
  {
    info: "Макаричев Семён Вячеславович",
    subject: "Немецкий язык",
    exam: "ЕГЭ",
    years: "10 лет",
    balls: "98",
    img: "",
    description: "Кислород водород и тд",
  },
  {
    info: "Макаричев Семён Вячеславович",
    subject: "Немецкий язык",
    exam: "ЕГЭ",
    years: "10 лет",
    balls: "98",
    img: "",
    description: "Кислород водород и тд",
  },
];
